### GET hae kaikki osoitteet
GET http://localhost:8080/customer-addresses

### GET hae osoite id:n perusteella
GET http://localhost:8080/customer-addresses/100002

### POST lisää uusi osoite
POST http://localhost:8080/customer-addresses
Content-Type: application/json

{
    "customerId": 100002,
    "street": "Uudenmaankatu 10",
    "postalCode": "00120",
    "city": "Helsinki",
    "country": "Finland"
}

### PUT päivittää osoitteen tietoja
PUT http://localhost:8080/customer-addresses/100002
Content-Type: application/json

{
    "customerId": 100002,
    "street": "Malminkaari 2",
    "postalCode": "00700",
    "city": "Helsinki",
    "country": "Finland"
}

### DELETE poistaa osoitteen id:n perusteella
DELETE http://localhost:8080/customer-addresses/100002