### GET hae kaikki asiakkaat
GET http://localhost:8080/customers

### GET hae asiakas id:n perusteella
GET http://localhost:8080/customers/100002

### POST uuden asiakkaan lisääminen (palauttaa dto objektin, jossa on id)
POST http://localhost:8080/customers
Content-Type: application/json

{
  "firstName": "testiukko",
  "lastName": "testinen",
  "email": "test@example.com",
  "phone": "05050443413"
}

### PUT päivittää asiakkaan tietoja (palauttaa dto objektin, jossa on id)
PUT http://localhost:8080/customers/100002
Content-Type: application/json

{
  "firstName": "pentti",
  "lastName": "ukko",
  "email": "penttiupdated@example.com",
  "phone": "+3585050443413"
}

### DELETE poistaa asiakkaan id:n perusteella
DELETE http://localhost:8080/customers/100002