### GET hae kaikki asiakkaat
GET http://localhost:8080/customers

### GET hae asiakas id:n perusteella
GET http://localhost:8080/customers/100005

### POST uuden asiakkaan lisääminen (palauttaa dto objektin, jossa on id)
POST http://localhost:8080/customers
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "testington",
  "email": "test@example.com",
  "phoneNumber": "0606606060"
}

### PUT päivittää asiakkaan tietoja (palauttaa dto objektin, jossa on id)
PUT http://localhost:8080/customers/100006
Content-Type: application/json

{
  "firstName": "isThis",
  "lastName": "Working",
  "email": "updated@example.com",
  "phoneNumber": "+3585050443413"
}

### DELETE poistaa asiakkaan id:n perusteella
DELETE http://localhost:8080/customers/100006